mode: gateway
grpc:
  address: ":8080"
health:
  address: ":8081"
gateway:
  routes:
    - store: primary
      target: dns:///sink-primary-engine:8080
      tls:
        insecure: true
shutdown_timeout: 15s
